### ISSUE TITLE
ged2doc crashes for some images

### ISSUE THREAD

**Issue by andy-z** [andy-z/ged2doc#13]
Got another error report on https://genery.com/ru/forum/viewtopic.php?f=11&t=4194&e=1&view=unread#p21350

* GEDCOM Utilities version: 0.1.11
* Python version: 
* Operating System: Windows

### Description

ged2doc crashes with a traceback

### What I Did

```
C:\Users\User\Desktop>ged2doc -l ru C:\Users\User\Desktop\111.ged 111.html
ERROR: ged2doc.cli (cli.py:230) -- caught exception: cannot write mode P as JPEG

Traceback (most recent call last):
File "D:\home\salnikov\My Documents\GitHub\venv-ged\lib\site-packages\PIL\JpegImagePlugin.py", line 620, in _save
KeyError: 'P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "d:\home\salnikov\my documents\github\ged2doc\ged2doc\cli.py", line 228, in main
File "d:\home\salnikov\my documents\github\ged2doc\ged2doc\writer.py", line 209, in save
File "d:\home\salnikov\my documents\github\ged2doc\ged2doc\html_writer.py", line 174, in _render_person
File "d:\home\salnikov\my documents\github\ged2doc\ged2doc\html_writer.py", line 326, in _getImageFragment
File "D:\home\salnikov\My Documents\GitHub\venv-ged\lib\site-packages\PIL\Image.py", line 1935, in save
File "D:\home\salnikov\My Documents\GitHub\venv-ged\lib\site-packages\PIL\JpegImagePlugin.py", line 622, in _save
OSError: cannot write mode P as JPEG
ERROR: ged2doc.cli (cli.py:231) -- Error while producing a document: cannot write mode P as JPEG
```

**Comment by andy-z** [comment]
Fixed by PR #14
