### ISSUE TITLE
Special case or invalid file?

### ISSUE THREAD

**Issue by FlominatorTM** [andy-z/ged2doc#17]
* GEDCOM Utilities version: 0.1.13 
* Python version: 3.6.1
* Operating System: Microsoft Windows [Version 10.0.16299.371]

### Description
I tried importing [the file in this file](https://github.com/andy-z/ged2doc/files/1984455/reprod.zip) that was generated by https://github.com/freeseek/getmyancestors/ with the result below: 

> ERROR: ged2doc.cli (cli.py:232) -- caught exception: Invalid syntax at line 400: `b'''
> Traceback (most recent call last):
>   File "c:\program files (x86)\python36-32\lib\site-packages\ged2doc\cli.py", line 230, in main
>     writer.save()
>   File "c:\program files (x86)\python36-32\lib\site-packages\ged2doc\writer.py", line 111, in save
>     for indi in reader.records0('INDI'):
>   File "c:\program files (x86)\python36-32\lib\site-packages\ged4py\parser.py", line 278, in records0
>     for offset, xtag in self.index0:
>   File "c:\program files (x86)\python36-32\lib\site-packages\ged4py\parser.py", line 171, in index0
>     self._init_index()
>   File "c:\program files (x86)\python36-32\lib\site-packages\ged4py\parser.py", line 196, in _init_index
>     for gline in self.gedcom_lines(self._bom_size):
>   File "c:\program files (x86)\python36-32\lib\site-packages\ged4py\parser.py", line 259, in gedcom_lines
>     "{0}: `{1}'".format(lineno, line))
> ged4py.parser.ParserError: Invalid syntax at line 400: `b'''
> ERROR: ged2doc.cli (cli.py:233) -- Error while producing a document: Invalid syntax at line 400: `b'''

Now the question is if the file has valid syntax.

### What I Did

```
getmyancestors.py -a 2 -i KF68-TC5 -o reprod.ged -v
ged2doc reprod.ged output.odt
```

**Comment by andy-slac** [comment]
The GEDCOM file is certainly broken, here is the record that `ged2doc` complains about:
```
0 @S26@ SOUR 
1 TITL LDS Film #0997667, #0997678, 
1 AUTH BIRTH:

1. LDS Film #0997667, Church Records (St. Maria Catholic Church), Kappelwindeck, Buehl, Baden, Germany, Vol. #3, Page 135.

BAPTISM:

2. LDS Film #0997667, Church Records (St. Maria Catholic Church), Kappelwindeck, Buehl, Baden, Germany, Vol. #3, Page 135.

DEATH:

3. Catholic Church Buehlertal, Baden, Germany, LDS Film #0997678, Church Records (St. Michael Catholic Church), Buehlertal, Baden, Germany, Vol. #2, Page 162, #13, .
Source Media Type: Microfilm.
""In Schonbuech on 15 April 1803, died is Adam Reith, spouse of Catharina Krauss, juryman in Schonbuech, 70 years, with sacraments of Eucharist and Extreme Unction provided. He was buried on 17 April 1803 in the parish Valle Buehlensis cemetery."."

BURIAL:

4. Catholic Church Buehlertal, Baden, Germany, LDS Film #0997678, Church Records (St. Michael Catholic Church), Buehlertal, Baden, Germany, Vol. #2, Page  162, #13, .
Source Media Type: Microfilm.

1 NOTE @N6@
1 REFN 9ZZB-CRH
```
It looks like AUTH record contains unprotected newlines which are stored verbatim. This needs to be stored using CONC/CONT GEDCOM tags. Please forward this to `getmyancestors`.

**Comment by FlominatorTM** [comment]
Thanks for the feedback, I forwarded it

**Comment by Linekio** [comment]
Please try this version : https://github.com/Linekio/getmyancestors
