### ISSUE TITLE
Failure in v2.0.0

### ISSUE THREAD

**Issue by andy-z** [andy-z/ged2doc#28]
Original report: https://genery.com/ru/forum/viewtopic.php?p=23808#p23808

Looks like there was something that I missed while migration to new Data classes in ged4py.

Would be nice to have a unit test which tests complete chain, I can probably copy one generic test file from ged4py_testdata here for that test.

**Comment by andy-z** [comment]
And the crash is:
```
$ ged2doc -vv ../ged4py_testdata/data/allged.ged allged.odt
...
DEBUG: ged2doc.cli (cli.py:263) -- caught exception: Can't instantiate abstract class DateValue with abstract methods __repr__, __str__, accept, kind
Traceback (most recent call last):
  File "/home/salnikov/project-ged/ged2doc/ged2doc/cli.py", line 260, in main
    writer.save()
  File "/home/salnikov/project-ged/ged2doc/ged2doc/writer.py", line 201, in save
    events = self._events(person)
  File "/home/salnikov/project-ged/ged2doc/ged2doc/writer.py", line 319, in _events
    for date, facts in sorted(events, key=_date_key):
  File "/home/salnikov/project-ged/ged2doc/ged2doc/writer.py", line 314, in _date_key
    date = model.DateValue()
TypeError: Can't instantiate abstract class DateValue with abstract methods __repr__, __str__, accept, kind
Error while producing a document:
  Can't instantiate abstract class DateValue with abstract methods __repr__, __str__, accept, kind
DEBUG: ged2doc.cli (cli.py:268) -- trying to remove output file: allged.odt
DEBUG: ged2doc.cli (cli.py:271) -- caught exception while removing file: [Errno 2] No such file or directory: 'allged.odt'
```

**Comment by andy-z** [comment]
Also trying to make HTML output:
```
$ ged2doc -vv ../ged4py_testdata/data/allged.ged allged.html
...
DEBUG: ged2doc.cli (cli.py:263) -- caught exception: module 'cgi' has no attribute 'escape'
Traceback (most recent call last):
  File "/home/salnikov/project-ged/ged2doc/ged2doc/cli.py", line 260, in main
    writer.save()
  File "/home/salnikov/project-ged/ged2doc/ged2doc/writer.py", line 105, in save
    self._render_section(1, 'personList', title)
  File "/home/salnikov/project-ged/ged2doc/ged2doc/html_writer.py", line 141, in _render_section
    cgi.escape(title))]
AttributeError: module 'cgi' has no attribute 'escape'
Error while producing a document:
  module 'cgi' has no attribute 'escape'
DEBUG: ged2doc.cli (cli.py:268) -- trying to remove output file: allged.html
```
This is probably due to py3 incompatibility.

**Comment by andy-z** [comment]
For latter need
```
import six
if not six.PY2:
    from html import escape as html_escape
else:
    from cgi import escape as html_escape
```
